export const bUsstops = [
  "Chrzanów Dworzec ZKKM",
  "Chrzanów Śródmieście",
  "Chrzanów Park",
  "Chrzanów Śląska",
  "Chrzanów Kąty I",
  "Chrzanów Kąty II",
  "Chrzanów Kąty Autostrada",
  "Cezarówka Dolna Autostrada",
  "Cezarówka Dolna",
  "Byczyna",
  "Bory Podgórska",
  "Bory Czysta",
  "Stadion Miejski",
  "Krakowska Pętla",
  "Urząd Miejski",
  "Centrum",
  "Leopold",
  "Urząd Skarbowy",
  "Osiedle Stałe",
  "Sosnowiec Jęzor Centrum Handlowe",
  "Katowice Os. Paderewskiego Graniczna",
  "Katowice Os. Paderewskiego Biblioteka Śląska",
  "Katowice Francuska",
  "Katowice Mariacka",
  "Katowice Szkolna",
  "Katowice Aleja Korfantego",
  "Katowice Strefa Kultury",
  "Sosnowiec Jęzor Centrum Handlowe",
  "Osiedle Stałe",
  "Urząd Skarbowy",
  "Urząd Miejski",
  "Krakowska Pętla",
  "Stadion Miejski",
  "Bory Czysta",
  "Bory Podgórska",
  "Cezarówka Dolna",
  "Cezarówka Dolna Autostrada",
  "Chrzanów Kąty Autostrada",
  "Chrzanów Kąty II",
  "Chrzanów Kąty I",
  "Chrzanów Śląska",
  "Chrzanów Ks. Skorupki",
  "Chrzanów Śródmieście",
  "Byczyna Astrów",
  "Byczyna Gwardzistów",
  "Bory Podgórska",
  "Bory Czysta",
  "Stadion Miejski",
  "Krakowska Pętla",
  "Rogatka",
  "Urząd Miejski",
  "Pechnik Cmentarz",
  "Pechnik",
  "Urząd Skarbowy",
  "Osiedle Stałe",
  "Osiedle Stałe Kalinowa",
  "Dąbrowa Narodowa Dąbrowska",
  "Dąbrowa Narodowa Kościół",
  "Łubowiec",
  "Sosnowiec Jęzor Centrum Handlowe",
  "Sosnowiec Niwka Kościół",
  "Mysłowice Kościół",
  "Mysłowice Katowicka",
  "Mysłowice Bończyka",
  "Katowice Strefa Kultury",
  "Katowice Aleja Korfantego",
  "Katowice Strefa Kultury",
  "Mysłowice Bończyka",
  "Mysłowice Kościół",
  "Sosnowiec Niwka Kościół",
  "Sosnowiec Jęzor Centrum Handlowe",
  "Dąbrowa Narodowa Kościół",
  "Dąbrowa Narodowa Dąbrowska",
  "Osiedle Stałe Kalinowa",
  "Osiedle Stałe",
  "Urząd Skarbowy",
  "Pechnik Cmentarz",
  "Urząd Miejski",
  "Krakowska Pętla",
  "Stadion Miejski",
  "Bory Czysta",
  "Bory Podgórska",
  "Byczyna Pętla",
  "Byczyna Gwardzistów",
  "Krakowska Pętla",
  "Urząd Miejski",
  "Pechnik Cmentarz",
  "Urząd Skarbowy",
  "Osiedle Stałe",
  "Osiedle Stałe Kalinowa",
  "Dąbrowa Narodowa Dąbrowska",
  "Dąbrowa Narodowa Kościół",
  "Sosnowiec Centrum Logistyczne",
  "Sosnowiec Jęzor Centrum Handlowe",
  "Sosnowiec Jęzor Jaworznicka",
  "Sosnowiec Niwka Kościół",
  "Mysłowice Kościół",
  "Mysłowice Katowicka",
  "Mysłowice Kopalnia",
  "Mysłowice Bończyka",
  "Katowice Wilhelmina Skrzyżowanie",
  "Katowice Zawodzie Ośrodek Sportowy",
  "Katowice Strefa Kultury",
  "Katowice Aleja Korfantego",
  "Katowice Strefa Kultury NOSPR",
  "Katowice Strefa Kultury",
  "Katowice Zawodzie Ośrodek Sportowy",
  "Katowice Wilhelmina Skrzyżowanie",
  "Mysłowice Bończyka",
  "Mysłowice Kopalnia",
  "Mysłowice Kościół",
  "Sosnowiec Niwka Kościół",
  "Sosnowiec Jęzor Jaworznicka",
  "Sosnowiec Jęzor Centrum Handlowe",
  "Sosnowiec Centrum Logistyczne",
  "Dąbrowa Narodowa Kościół",
  "Dąbrowa Narodowa Dąbrowska",
  "Osiedle Stałe Kalinowa",
  "Osiedle Stałe",
  "Urząd Skarbowy",
  "Pechnik Cmentarz",
  "Urząd Miejski",
  "Krakowska Pętla",
  "Urząd Miejski",
  "Pechnik Cmentarz",
  "Urząd Skarbowy",
  "Osiedle Stałe",
  "Osiedle Stałe Kalinowa",
  "Dąbrowa Narodowa Dąbrowska",
  "Dąbrowa Narodowa Kościół",
  "Sosnowiec Centrum Logistyczne",
  "Sosnowiec Jęzor Centrum Handlowe",
  "Sosnowiec Jęzor Jaworznicka",
  "Sosnowiec Niwka Kościół",
  "Sosnowiec Modrzejów Rynek",
  "Sosnowiec Niwka Baza",
  "Sosnowiec Niwka Kolonia Staszic",
  "Sosnowiec Dębowa Góra Kolonia Ludmiła",
  "Sosnowiec Dębowa Góra Ogródki Działkowe",
  "Sosnowiec Dębowa Góra Wiadukt",
  "Sosnowiec Rondo Ludwik",
  "Sosnowiec Ostrogórska",
  "Sosnowiec Jagiellońska",
  "Sosnowiec Jagiellońska Kościół",
  "Sosnowiec Kościelna",
  "Sosnowiec Wspólna",
  "Sosnowiec Dworzec PKP",
  "Sosnowiec Pogoń Orla",
  "Sosnowiec Pogoń Kościół",
  "Sosnowiec Pogoń Akademiki",
  "Sosnowiec Szpital Wojewódzki",
  "Sosnowiec Szpital Wojewódzki",
  "Sosnowiec Pogoń Akademiki",
  "Sosnowiec Pogoń Klub Kiepury",
  "Sosnowiec Pogoń Orla",
  "Sosnowiec Urząd Miasta",
  "Sosnowiec Dworzec PKP",
  "Sosnowiec Wspólna",
  "Sosnowiec Kościelna",
  "Sosnowiec Jagiellońska Kościół",
  "Sosnowiec Jagiellońska",
  "Sosnowiec Ostrogórska",
  "Sosnowiec Rondo Ludwik",
  "Sosnowiec Dębowa Góra Wiadukt",
  "Sosnowiec Dębowa Góra Ogródki Działkowe",
  "Sosnowiec Dębowa Góra Kolonia Ludmiła",
  "Sosnowiec Niwka Kolonia Staszic",
  "Sosnowiec Niwka Baza",
  "Sosnowiec Modrzejów Rynek",
  "Sosnowiec Niwka Kościół",
  "Sosnowiec Jęzor Jaworznicka",
  "Sosnowiec Jęzor Centrum Handlowe",
  "Sosnowiec Centrum Logistyczne",
  "Dąbrowa Narodowa Kościół",
  "Dąbrowa Narodowa Dąbrowska",
  "Osiedle Stałe Kalinowa",
  "Osiedle Stałe",
  "Urząd Skarbowy",
  "Pechnik Cmentarz",
  "Urząd Miejski",
  "Krakowska Pętla",
  "Urząd Miejski",
  "Rynek",
  "Warpie Wodociągi",
  "Warpie Galmany",
  "Warpie",
  "Geosfera",
  "Góra Piasku Kaliska",
  "Góra Piasku",
  "Szczakowa Polna",
  "Szczakowa Osiedle Gagarina",
  "Szczakowa Przychodnia",
  "Szczakowa Dworzec PKP",
  "Szczakowa Przychodnia",
  "Szczakowa Kościół",
  "Szczakowa Cmentarz",
  "Dobra Pompy",
  "Dobra",
  "Dobra Pętla",
  "Dobra Pompy",
  "Szczakowa Cmentarz",
  "Park Gródek",
  "Pieczyska Szkoła",
  "Pieczyska Solskiego",
  "Park Gródek",
  "Szczakowa Cmentarz",
  "Park Gródek",
  "Pieczyska Szkoła",
  "Pieczyska Solskiego",
  "Park Gródek",
  "Szczakowa Cmentarz",
  "Dobra Pompy",
  "Dobra Pętla",
  "Dobra Pompy",
  "Szczakowa Cmentarz",
  "Szczakowa Kościół",
  "Szczakowa Przychodnia",
  "Szczakowa Dworzec PKP",
  "Szczakowa Przychodnia",
  "Szczakowa Osiedle Gagarina",
  "Szczakowa Polna",
  "Góra Piasku",
  "Góra Piasku Kaliska",
  "Warpie Galmany",
  "Warpie Wodociągi",
  "Obrońców Poczty Gdańskiej",
  "Biblioteka",
  "Urząd Miejski",
  "Krakowska Pętla",
  "Urząd Miejski",
  "Pechnik Cmentarz",
  "Urząd Skarbowy",
  "Szczakowska",
  "Niedzieliska Wiejska",
  "Niedzieliska Klub Relaks",
  "Niedzieliska",
  "Chropaczówka",
  "Chropaczówka II",
  "Długoszyn Upadowa",
  "Długoszyn",
  "Długoszyn Dąbrowskiego",
  "Borowiec Dąbrowskiego",
  "Borowiec Moździerzowców Szkoła",
  "Borowiec Moździerzowców II",
  "Borowiec Moździerzowców I",
  "Szczakowa Osiedle Gagarina",
  "Szczakowa Przychodnia",
  "Szczakowa Dworzec PKP",
  "Szczakowa Przychodnia",
  "Szczakowa Osiedle Gagarina",
  "Borowiec Moździerzowców I",
  "Borowiec Moździerzowców II",
  "Borowiec Moździerzowców Szkoła",
  "Borowiec Dąbrowskiego",
  "Długoszyn Dąbrowskiego",
  "Długoszyn Upadowa",
  "Chropaczówka II",
  "Niedzieliska Klub Relaks",
  "Niedzieliska Wiejska",
  "Urząd Skarbowy",
  "Pechnik Cmentarz",
  "Urząd Miejski",
  "Szczakowa Bukowska Pętla",
  "Szczakowa Bukowska",
  "Szczakowa Dworzec PKP",
  "Szczakowa Przychodnia",
  "Szczakowa Osiedle Gagarina",
  "Szczakowa Polna",
  "Góra Piasku",
  "Góra Piasku Kaliska",
  "Osiedle Sfera",
  "Niedzieliska Klub Relaks",
  "Niedzieliska Wiejska",
  "Urząd Skarbowy",
  "Pechnik Cmentarz",
  "Rzemieślnicza",
  "Matejki",
  "Pechnik Cmentarz",
  "Urząd Skarbowy",
  "Niedzieliska Wiejska",
  "Niedzieliska Klub Relaks",
  "Osiedle Sfera",
  "Góra Piasku Kaliska",
  "Góra Piasku",
  "Szczakowa Polna",
  "Szczakowa Osiedle Gagarina",
  "Szczakowa Przychodnia",
  "Szczakowa Dworzec PKP",
  "Szczakowa Bukowska",
  "Energetyków",
  "Siłownia",
  "Wojska Polskiego",
  "Osiedle Stałe",
  "Niedzieliska Wiejska",
  "Niedzieliska Klub Relaks",
  "Chropaczówka II",
  "Długoszyn Upadowa",
  "Długoszyn Dąbrowskiego",
  "Borowiec Dąbrowskiego",
  "Góra Piasku Batorego Szkoła",
  "Góra Piasku",
  "Szczakowa Polna",
  "Szczakowa Osiedle Gagarina",
  "Szczakowa Przychodnia",
  "Szczakowa Dworzec PKP",
  "Szczakowa Przychodnia",
  "Szczakowa Osiedle Gagarina",
  "Szczakowa Polna",
  "Góra Piasku",
  "Góra Piasku Batorego Szkoła",
  "Borowiec Dąbrowskiego",
  "Długoszyn Dąbrowskiego",
  "Długoszyn Upadowa",
  "Chropaczówka II",
  "Niedzieliska Klub Relaks",
  "Niedzieliska Wiejska",
  "Osiedle Stałe",
  "Wojska Polskiego",
  "Krakowska Pętla",
  "Stadion Miejski",
  "Bory Niemcewicza",
  "Bory Tetmajera",
  "Bory Bielany",
  "Bory Stroma",
  "Bory Zakole",
  "Bory Hetmańska",
  "Bory Hetmańska Pętla",
  "Bory Hetmańska",
  "Bory Zakole",
  "Bory Bielańska",
  "Bory Rondo",
  "Stara Huta Reja",
  "Stara Huta",
  "Stara Huta Fabryczna",
  "Stara Huta Spacerowa",
  "Matejki Arkady",
  "Podwale",
  "Podwale Liceum",
  "Podwale Licealna",
  "Podwale 11 Listopada",
  "Podłęże Przychodnia",
  "Podłęże Osiedle",
  "Podłęże Przychodnia",
  "Urząd Skarbowy",
  "Osiedle Stałe",
  "Osiedle Stałe Armii Krajowej",
  "Osiedle Stałe Sempołowskiej",
  "Dąbrowa Narodowa Długoszyńska II",
  "Dąbrowa Narodowa Storczyków",
  "Osiedle Stałe Cmentarz Pętla",
  "Osiedle Stałe Cmentarz Pętla",
  "Dąbrowa Narodowa Storczyków",
  "Dąbrowa Narodowa Długoszyńska II",
  "Osiedle Stałe Sempołowskiej",
  "Osiedle Stałe Armii Krajowej",
  "Osiedle Stałe",
  "Urząd Skarbowy",
  "Podłęże Przychodnia",
  "Podłęże Osiedle",
  "Podłęże Przychodnia",
  "Podwale 11 Listopada",
  "Podwale Licealna",
  "Podwale Liceum",
  "Plac Św. Jana",
  "Matejki Arkady",
  "Stara Huta Spacerowa",
  "Stara Huta Fabryczna",
  "Stara Huta",
  "Stara Huta Reja",
  "Bory Rondo",
  "Bory Zakole",
  "Bory Hetmańska",
  "Bory Hetmańska Pętla",
  "Bory Hetmańska",
  "Bory Zakole",
  "Bory Bielańska",
  "Bory Stroma",
  "Bory Bielany",
  "Bory Tetmajera",
  "Bory Niemcewicza",
  "Stadion Miejski",
  "Krakowska Pętla",
  "Urząd Miejski",
  "Matejki Arkady",
  "Stara Huta Spacerowa",
  "Azot Osiedle",
  "Organika",
  "Azot",
  "Szyb Sobieski",
  "Sobieski Pętla",
  "Jeleń Lipinka",
  "Jeleń Cmentarz",
  "Jeleń Rynek",
  "Jeleń Kościół",
  "Jeleń Dolna",
  "Jeleń Wielki Dół",
  "Jeleń Łęg Pawilon",
  "Jeleń Rynek",
  "Jeleń Przedszkole",
  "Jeleń Dom Kultury",
  "Jeleń Szkoła",
  "Jeleń Piekarnia",
  "Jeleń Centrum Handlowe",
  "Jeleń Park Przemysłowy",
  "Jeleń Dąb Leśniczówka",
  "Jeleń Dąb Sklep",
  "Jeleń Dąb Pętla",
  "Jeleń Łęg Pętla",
  "Jeleń Łęg Pawilon",
  "Jeleń Wielki Dół",
  "Jeleń Dolna",
  "Jeleń Kościół",
  "Jeleń Rynek",
  "Jeleń Dąb Pętla",
  "Jeleń Dąb Sklep",
  "Jeleń Dąb Leśniczówka",
  "Jeleń Park Przemysłowy",
  "Jeleń Centrum Handlowe",
  "Jeleń Piekarnia",
  "Jeleń Szkoła",
  "Jeleń Banasika",
  "Jeleń Dom Kultury",
  "Jeleń Przedszkole",
  "Jeleń Rynek",
  "Jeleń Cmentarz",
  "Jeleń Lipinka",
  "Sobieski Pętla",
  "Szyb Sobieski",
  "Azot Osiedle",
  "Stara Huta Spacerowa",
  "Matejki Arkady",
  "Urząd Miejski",
  "Podłęże Osiedle",
  "Podłęże Kościół",
  "Podłęże Szkoła",
  "Moniuszki",
  "Chełmońskiego",
  "Szpital",
  "Chełmońskiego Pompy",
  "Wilkoszyn Chełmońskiego",
  "Ciężkowice Dęby",
  "Ciężkowice Kapliczka",
  "Ciężkowice Górka",
  "Ciężkowice Turystyczna",
  "Ciężkowice Stadion",
  "Ciężkowice Dworzec Kolejowy",
  "Ciężkowice Braci Śniadeckich",
  "Ciężkowice Szkoła",
  "Ciężkowice Kościół",
  "Ciężkowice Bagienko",
  "Ciężkowice Bagienko",
  "Ciężkowice Filomatów",
  "Ciężkowice Młyny Serafińskie",
  "Ciężkowice Grabańka",
  "Ciężkowice Pętla",
  "Ciężkowice Bagienko",
  "Ciężkowice Kościół",
  "Ciężkowice Szkoła",
  "Ciężkowice Leśniczówka",
  "Ciężkowice Klinowa",
  "Ciężkowice Wakacyjna",
  "Ciężkowice Bobrowa Górka",
  "Pieczyska Sobieskiego",
  "Pieczyska Szkoła",
  "Pieczyska Solskiego",
  "Park Gródek",
  "Szczakowa Cmentarz",
  "Szczakowa Kościół",
  "Szczakowa Przychodnia",
  "Szczakowa Dworzec PKP",
  "Szczakowa Przychodnia",
  "Szczakowa Kościół",
  "Szczakowa Cmentarz",
  "Park Gródek",
  "Pieczyska Szkoła",
  "Pieczyska Solskiego",
  "Pieczyska Sobieskiego",
  "Ciężkowice Bobrowa Górka",
  "Ciężkowice Wakacyjna",
  "Ciężkowice Klinowa",
  "Ciężkowice Leśniczówka",
  "Ciężkowice Szkoła",
  "Ciężkowice Kościół",
  "Ciężkowice Bagienko",
  "Ciężkowice Filomatów",
  "Ciężkowice Młyny Serafińskie",
  "Ciężkowice Grabańka",
  "Ciężkowice Pętla",
  "Ciężkowice Bagienko",
  "Ciężkowice Kościół",
  "Ciężkowice Szkoła",
  "Ciężkowice Braci Śniadeckich",
  "Ciężkowice Dworzec Kolejowy",
  "Ciężkowice Stadion",
  "Ciężkowice Turystyczna",
  "Ciężkowice Górka",
  "Ciężkowice Kapliczka",
  "Ciężkowice Dęby",
  "Wilkoszyn Chełmońskiego",
  "Chełmońskiego Pompy",
  "Obrońców Poczty Gdańskiej",
  "Zielona",
  "Podłęże Szkoła",
  "Podłęże Kościół",
  "Chrzanów Dworzec ZKKM",
  "Chrzanów Śródmieście",
  "Chrzanów Park",
  "Chrzanów Ks. Skorupki",
  "Chrzanów Działki",
  "Chrzanów Tuczarnia",
  "Chrzanów Balin Kościół",
  "Chrzanów Balin Bar",
  "Chrzanów Balin Szkoła",
  "Chrzanów Balin Wolności",
  "Koźmin",
  "Koźmin Jesienna",
  "Koźmin Las",
  "Jeziorki Herbowa",
  "Jeziorki Kasztanowa",
  "Jeziorki Kościół",
  "Jeziorki Sklep",
  "Jeziorki Szkoła",
  "Jeziorki Dożynkowa",
  "Wilkoszyn Cmentarz",
  "Wilkoszyn",
  "Wilkoszyn Chełmońskiego",
  "Chełmońskiego Pompy",
  "Obrońców Poczty Gdańskiej",
  "Podwale Liceum",
  "Podwale Licealna",
  "Podwale 11 Listopada",
  "Urząd Skarbowy",
  "Osiedle Stałe",
  "Osiedle Stałe Kalinowa",
  "Dąbrowa Narodowa Dąbrowska",
  "Dąbrowa Narodowa Kościół",
  "Łubowiec Pętla",
  "Dąbrowa Narodowa Kościół",
  "Dąbrowa Narodowa Dąbrowska",
  "Osiedle Stałe Kalinowa",
  "Osiedle Stałe",
  "Urząd Skarbowy",
  "Podwale 11 Listopada",
  "Podwale Licealna",
  "Podwale Liceum",
  "Plac Św. Jana",
  "Chełmońskiego Pompy",
  "Wilkoszyn Chełmońskiego",
  "Wilkoszyn Cmentarz",
  "Jeziorki Dożynkowa",
  "Jeziorki Szkoła",
  "Jeziorki Sklep",
  "Jeziorki Kościół",
  "Jeziorki Kasztanowa",
  "Jeziorki Herbowa",
  "Koźmin Las",
  "Koźmin Jesienna",
  "Chrzanów Balin Szkoła",
  "Chrzanów Balin Bar",
  "Chrzanów Balin Kościół",
  "Chrzanów Tuczarnia",
  "Chrzanów Działki",
  "Chrzanów Śródmieście",
  "Krakowska Pętla",
  "Urząd Miejski",
  "Podłęże Szkoła",
  "Podłęże Stadion",
  "Martyniaków Przejazd",
  "Elektrownia Zespół Szkół",
  "Elektrownia Parking",
  "Elektrownia Parking",
  "Elektrownia Zespół Szkół",
  "Martyniaków Przejazd",
  "Podłęże Stadion",
  "Podłęże Szkoła",
  "Urząd Miejski",
  "Warpie Wodociągi",
  "Chełmońskiego Pompy",
  "Wilkoszyn Chełmońskiego",
  "Wilkoszyn Cmentarz",
  "Jeziorki Dożynkowa",
  "Jeziorki Szkoła",
  "Jeziorki Sklep",
  "Jeziorki Kościół",
  "Jeziorki Kasztanowa",
  "Cezarówka Górna Sasanek",
  "Cezarówka Górna Pętla",
  "Cezarówka Górna Pętla",
  "Cezarówka Górna Sasanek",
  "Jeziorki Kasztanowa",
  "Jeziorki Kościół",
  "Jeziorki Sklep",
  "Jeziorki Szkoła",
  "Jeziorki Dożynkowa",
  "Wilkoszyn Cmentarz",
  "Wilkoszyn Chełmońskiego",
  "Chełmońskiego Pompy",
  "Warpie Wodociągi",
  "Plac Św. Jana",
  "Szczakowa Dworzec PKP",
  "Szczakowa Przychodnia",
  "Szczakowa Osiedle Gagarina",
  "Szczakowa Polna",
  "Góra Piasku",
  "Góra Piasku Batorego Szkoła",
  "Borowiec Dąbrowskiego",
  "Długoszyn Dąbrowskiego",
  "Długoszyn Upadowa",
  "Chropaczówka II",
  "Niedzieliska Klub Relaks",
  "Niedzieliska Wiejska",
  "Urząd Skarbowy",
  "Podłęże Przychodnia",
  "Podłęże Osiedle",
  "Podłęże Kościół",
  "Podłęże Stadion",
  "Martyniaków Przejazd",
  "Elektrownia Zespół Szkół",
  "Elektrownia Parking",
  "Elektrownia Zespół Szkół",
  "Martyniaków Przejazd",
  "Podłęże Stadion",
  "Podłęże Kościół",
  "Podłęże Osiedle",
  "Podłęże Przychodnia",
  "Urząd Skarbowy",
  "Niedzieliska Wiejska",
  "Niedzieliska Klub Relaks",
  "Chropaczówka II",
  "Długoszyn Upadowa",
  "Długoszyn Dąbrowskiego",
  "Borowiec Dąbrowskiego",
  "Góra Piasku Batorego Szkoła",
  "Góra Piasku",
  "Szczakowa Polna",
  "Szczakowa Osiedle Gagarina",
  "Szczakowa Przychodnia",
  "Elektrownia Zespół Szkół",
  "Elektrownia",
  "Promienna",
  "Strefa Przemysłowa II",
  "Strefa Przemysłowa III",
  "Dąbrowa Narodowa Lema",
  "Darwina",
  "Martyniaków",
  "Martyniaków Przejazd",
  "Podłęże Stadion",
  "Podłęże Kościół",
  "Podłęże Osiedle",
  "Podłęże Przychodnia",
  "Pechnik Cmentarz",
  "Chełmońskiego Pompy",
  "Wilkoszyn Chełmońskiego",
  "Ciężkowice Dęby",
  "Ciężkowice Kapliczka",
  "Ciężkowice Górka",
  "Ciężkowice Turystyczna",
  "Ciężkowice Stadion",
  "Ciężkowice Dworzec Kolejowy",
  "Ciężkowice Braci Śniadeckich",
  "Ciężkowice Szkoła",
  "Ciężkowice Kościół",
  "Ciężkowice Bagienko",
  "Ciężkowice Filomatów",
  "Ciężkowice Młyny Serafińskie",
  "Ciężkowice Grabańka",
  "Ciężkowice Pętla",
  "Ciężkowice Bagienko",
  "Ciężkowice Kościół",
  "Ciężkowice Szkoła",
  "Ciężkowice Leśniczówka",
  "Ciężkowice Klinowa",
  "Ciężkowice Wakacyjna",
  "Ciężkowice Bobrowa Górka",
  "Pieczyska Sobieskiego",
  "Pieczyska Szkoła",
  "Pieczyska Solskiego",
  "Park Gródek",
  "Szczakowa Cmentarz",
  "Szczakowa Kościół",
  "Szczakowa Przychodnia",
  "Szczakowa Dworzec PKP",
  "Szczakowa Przychodnia",
  "Szczakowa Kościół",
  "Szczakowa Cmentarz",
  "Park Gródek",
  "Pieczyska Szkoła",
  "Pieczyska Solskiego",
  "Pieczyska Sobieskiego",
  "Ciężkowice Bobrowa Górka",
  "Ciężkowice Wakacyjna",
  "Ciężkowice Klinowa",
  "Ciężkowice Leśniczówka",
  "Ciężkowice Szkoła",
  "Ciężkowice Kościół",
  "Ciężkowice Bagienko",
  "Ciężkowice Filomatów",
  "Ciężkowice Młyny Serafińskie",
  "Ciężkowice Grabańka",
  "Ciężkowice Pętla",
  "Ciężkowice Bagienko",
  "Ciężkowice Kościół",
  "Ciężkowice Szkoła",
  "Ciężkowice Braci Śniadeckich",
  "Ciężkowice Dworzec Kolejowy",
  "Ciężkowice Stadion",
  "Ciężkowice Turystyczna",
  "Ciężkowice Górka",
  "Ciężkowice Kapliczka",
  "Ciężkowice Dęby",
  "Wilkoszyn Chełmońskiego",
  "Chełmońskiego Pompy",
  "Obrońców Poczty Gdańskiej",
  "Pechnik Cmentarz",
  "Podłęże Przychodnia",
  "Podłęże Osiedle",
  "Podłęże Kościół",
  "Podłęże Stadion",
  "Martyniaków Przejazd",
  "Dąbrowa Narodowa Lema",
  "Strefa Przemysłowa III",
  "Strefa Przemysłowa II",
  "Cezarówka Dolna Pętla",
  "Cezarówka Dolna",
  "Byczyna Kaczeńców II",
  "Byczyna Kaczeńców I",
  "Byczyna Dom Handlowy",
  "Byczyna Dom Kultury",
  "Bory Podgórska",
  "Bory Czysta",
  "Stadion Miejski",
  "Krakowska Pętla",
  "Urząd Miejski",
  "Pechnik Cmentarz",
  "Urząd Skarbowy",
  "Osiedle Stałe",
  "Urząd Skarbowy",
  "Pechnik Cmentarz",
  "Urząd Miejski",
  "Krakowska Pętla",
  "Stadion Miejski",
  "Bory Czysta",
  "Bory Podgórska",
  "Byczyna Dom Kultury",
  "Byczyna Dom Handlowy",
  "Byczyna Kaczeńców I",
  "Byczyna Kaczeńców II",
  "Cezarówka Dolna",
  "Krakowska Pętla",
  "Urząd Miejski",
  "Matejki Arkady",
  "Stara Huta Spacerowa",
  "Stara Huta Fabryczna",
  "Szyb Sobieski",
  "Sobieski Pętla",
  "Jeleń Lipinka",
  "Jeleń Cmentarz",
  "Jeleń Rynek",
  "Jeleń Przedszkole",
  "Jeleń Dom Kultury",
  "Jeleń Szkoła",
  "Jeleń Piekarnia",
  "Jeleń Inwestycyjna",
  "Jeleń Okrągle Skrzyżowanie",
  "Jeleń Okrągle Kapliczka",
  "Byczyna Abstorskich",
  "Byczyna Rewolucjonistów",
  "Bory Podgórska",
  "Bory Czysta",
  "Stadion Miejski",
  "Byczyna Pętla",
  "Byczyna Rewolucjonistów",
  "Byczyna Abstorskich",
  "Jeleń Okrągle Kapliczka",
  "Jeleń Okrągle Skrzyżowanie",
  "Jeleń Inwestycyjna",
  "Jeleń Piekarnia",
  "Jeleń Szkoła",
  "Jeleń Dom Kultury",
  "Jeleń Przedszkole",
  "Jeleń Rynek",
  "Jeleń Cmentarz",
  "Jeleń Lipinka",
  "Sobieski Pętla",
  "Szyb Sobieski",
  "Stara Huta Fabryczna",
  "Stara Huta Spacerowa",
  "Matejki Arkady",
  "Urząd Miejski",
  "Krakowska Pętla",
  "Stadion Miejski",
  "Bory Czysta",
  "Bory Podgórska",
  "Sobieski Pętla",
  "Szyb Sobieski",
  "Azot Młynarska",
  "Pszczelnik",
  "Piaskowa",
  "Podłęże Kościół",
  "Podłęże Osiedle",
  "Podłęże Przychodnia",
  "Gigant Bogusławskiego",
  "Gigant Złota",
  "Gigant Osiedle",
  "Gigant Bogusławskiego Przychodnia",
  "Pechnik Cmentarz",
  "Urząd Miejski",
  "Insurekcji Kościuszkowskiej",
  "Osiedle Skałka",
  "Krakowska Pętla",
  "Osiedle Skałka",
  "Insurekcji Kościuszkowskiej",
  "Urząd Miejski",
  "Pechnik Cmentarz",
  "Gigant Bogusławskiego",
  "Gigant Złota",
  "Gigant Osiedle",
  "Gigant Bogusławskiego Przychodnia",
  "Podłęże Przychodnia",
  "Podłęże Osiedle",
  "Podłęże Kościół",
  "Azot Młynarska",
  "Szyb Sobieski",
  "Krakowska Pętla",
  "Osiedle Skałka",
  "Insurekcji Kościuszkowskiej",
  "Urząd Miejski",
  "Podwale Liceum",
  "Podwale Działkowa",
  "Gigant Bogusławskiego Przychodnia",
  "Gigant Bogusławskiego",
  "Gigant Złota",
  "Wiejska Kościół",
  "Mylna",
  "Niedzieliska Wiejska",
  "Osiedle Stałe",
  "Wojska Polskiego",
  "Martyniaków Przejazd",
  "Elektrownia Zespół Szkół",
  "Wysoki Brzeg",
  "Wysoki Brzeg Pętla",
  "Wysoki Brzeg Pętla",
  "Wysoki Brzeg",
  "Elektrownia Parking",
  "Elektrownia Zespół Szkół",
  "Martyniaków Przejazd",
  "Wojska Polskiego",
  "Osiedle Stałe",
  "Niedzieliska Wiejska",
  "Wiejska Kościół",
  "Gigant Osiedle",
  "Podwale Działkowa",
  "Podwale Liceum",
  "Plac Św. Jana",
  "Urząd Miejski",
  "Insurekcji Kościuszkowskiej",
  "Osiedle Skałka",
  "Szczotki Pętla",
  "Dąbrowa Narodowa Brzozowa",
  "Dąbrowa Narodowa Długa",
  "Dąbrowa Narodowa Spółdzielcza",
  "Dąbrowa Narodowa Starowiejska",
  "Dąbrowa Narodowa Kapliczka",
  "Osiedle Stałe Starowiejska",
  "Osiedle Stałe Armii Krajowej",
  "Osiedle Stałe",
  "Urząd Skarbowy",
  "Podłęże Przychodnia",
  "Podłęże Osiedle",
  "Podłęże Towarowa II",
  "Podłęże Towarowa I",
  "Podłęże Brodzińskiego",
  "Podłęże Fredry",
  "Kolejowa",
  "Urząd Miejski",
  "Insurekcji Kościuszkowskiej",
  "Obwodnica Północna Rondo",
  "Dom Pomocy Społecznej",
  "Szpital Pętla",
  "Szpital Pętla",
  "Obrońców Poczty Gdańskiej",
  "Dom Pomocy Społecznej",
  "Obwodnica Północna Rondo",
  "Insurekcji Kościuszkowskiej",
  "Urząd Miejski",
  "Podłęże Fredry",
  "Podłęże Brodzińskiego",
  "Podłęże Towarowa I",
  "Podłęże Towarowa II",
  "Podłęże Osiedle",
  "Podłęże Przychodnia",
  "Urząd Skarbowy",
  "Osiedle Stałe",
  "Osiedle Stałe Armii Krajowej",
  "Osiedle Stałe Starowiejska",
  "Dąbrowa Narodowa Kapliczka",
  "Dąbrowa Narodowa Starowiejska",
  "Dąbrowa Narodowa Spółdzielcza",
  "Dąbrowa Narodowa Długa",
  "Dąbrowa Narodowa Brzozowa",
  "Łubowiec Cmentarz Pętla",
  "Łubowiec Osiedle",
  "Dąbrowa Narodowa Emilii Plater",
  "Dąbrowa Narodowa Kościół",
  "Dąbrowa Narodowa Długoszyńska",
  "Osiedle Stałe Starowiejska",
  "Osiedle Stałe Armii Krajowej",
  "Osiedle Stałe",
  "Urząd Skarbowy",
  "Podłęże Przychodnia",
  "Podłęże Osiedle",
  "Podłęże Towarowa II",
  "Podłęże Towarowa I",
  "Podłęże Brodzińskiego",
  "Podłęże Fredry",
  "Urząd Miejski",
  "Insurekcji Kościuszkowskiej",
  "Obwodnica Północna Rondo",
  "Dom Pomocy Społecznej",
  "Szpital Pętla",
  "Obrońców Poczty Gdańskiej",
  "Dom Pomocy Społecznej",
  "Obwodnica Północna Rondo",
  "Insurekcji Kościuszkowskiej",
  "Urząd Miejski",
  "Podłęże Fredry",
  "Podłęże Brodzińskiego",
  "Podłęże Towarowa I",
  "Podłęże Towarowa II",
  "Podłęże Osiedle",
  "Podłęże Przychodnia",
  "Urząd Skarbowy",
  "Osiedle Stałe",
  "Osiedle Stałe Armii Krajowej",
  "Osiedle Stałe Starowiejska",
  "Dąbrowa Narodowa Długoszyńska",
  "Dąbrowa Narodowa Kościół",
  "Dąbrowa Narodowa Emilii Plater",
  "Łubowiec Osiedle",
  "Gigant Osiedle",
  "Podwale Działkowa",
  "Podwale Liceum",
  "Plac Św. Jana",
  "Chełmońskiego Pompy",
  "Wilkoszyn Chełmońskiego",
  "Wilkoszyn Cmentarz",
  "Jeziorki Dożynkowa",
  "Jeziorki Szkoła",
  "Jeziorki Sklep",
  "Jeziorki Kościół",
  "Byczyna Astrów",
  "Byczyna Gwardzistów",
  "Byczyna Pętla",
  "Byczyna Rewolucjonistów",
  "Byczyna Abstorskich",
  "Jeleń Okrągle Kapliczka",
  "Jeleń Okrągle Skrzyżowanie",
  "Jeleń Inwestycyjna",
  "Jeleń Piekarnia",
  "Jeleń Szkoła",
  "Jeleń Dom Kultury",
  "Jeleń Przedszkole",
  "Jeleń Rynek",
  "Jeleń Kościół",
  "Jeleń Dolna",
  "Jeleń Wielki Dół",
  "Jeleń Łęg Pawilon",
  "Jeleń Łęg Pętla",
  "Jeleń Łęg Pawilon",
  "Jeleń Wielki Dół",
  "Jeleń Dolna",
  "Jeleń Kościół",
  "Jeleń Rynek",
  "Jeleń Przedszkole",
  "Jeleń Dom Kultury",
  "Jeleń Szkoła",
  "Jeleń Piekarnia",
  "Jeleń Inwestycyjna",
  "Jeleń Okrągle Skrzyżowanie",
  "Jeleń Okrągle Kapliczka",
  "Byczyna Abstorskich",
  "Byczyna Rewolucjonistów",
  "Byczyna Pętla",
  "Byczyna Gwardzistów",
  "Byczyna Astrów",
  "Jeziorki Kościół",
  "Jeziorki Sklep",
  "Jeziorki Szkoła",
  "Jeziorki Dożynkowa",
  "Wilkoszyn Cmentarz",
  "Wilkoszyn Chełmońskiego",
  "Chełmońskiego Pompy",
  "Obrońców Poczty Gdańskiej",
  "Podwale Liceum",
  "Podwale Działkowa",
  "Gigant Bogusławskiego Przychodnia",
  "Gigant Bogusławskiego",
  "Gigant Złota",
  "Krakowska Pętla",
  "Urząd Miejski",
  "Pechnik Cmentarz",
  "Urząd Skarbowy",
  "Osiedle Stałe",
  "Osiedle Stałe",
  "Niedzieliska Wiejska",
  "Niedzieliska Klub Relaks",
  "Osiedle Sfera",
  "Góra Piasku Kaliska",
  "Góra Piasku",
  "Szczakowa Polna",
  "Szczakowa Osiedle Gagarina",
  "Szczakowa Cmentarz",
  "Park Gródek",
  "Szczakowa Cmentarz",
  "Zalew Sosina",
  "Zalew Sosina",
  "Szczakowa Cmentarz",
  "Park Gródek",
  "Szczakowa Cmentarz",
  "Szczakowa Osiedle Gagarina",
  "Szczakowa Polna",
  "Góra Piasku",
  "Góra Piasku Kaliska",
  "Osiedle Sfera",
  "Niedzieliska Klub Relaks",
  "Niedzieliska Wiejska",
  "Osiedle Stałe",
  "Osiedle Stałe",
  "Urząd Skarbowy",
  "Pechnik Cmentarz",
  "Urząd Miejski",
]
